// Auto-generated by scripts/generate-tile-doc-content.ts -- DO NOT EDIT

import type { TileDocContent } from "@wendoo/assistant-bridge/kit";

/**
 * The English documentation this target ships for its own tiles, as raw
 * markdown keyed by content key: the base name, without its `.md` extension,
 * of the file that carries it.
 */
export const MICROBIT_V2_TILE_DOC_CONTENT: TileDocContent = {
  "actuator-display-clear": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Clear display

Turns off every LED of the 5x5 display.

---

Turns off all 25 LEDs at once, leaving the display blank. It takes no settings.
The clear is instant and takes over the display right away, ending a running
text scroll or image draw.
`,
  "actuator-display-text": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Display text

Scrolls text across the display.

---

Scrolls the text from right to left and ends with a blank display; a single
character is shown still for a moment instead of scrolling. With no
\`tile:tile.parameter->microbit-v2.text\` argument it shows the value the WHEN
side produced, or "hello". The rule waits until the animation finishes, and a
request made while the display is busy is dropped; add
\`tile:tile.modifier->microbit-v2.immediately\` to take over the display at once,
or \`tile:tile.modifier->microbit-v2.in-background\` to let the rule continue
without waiting.
`,
  "actuator-draw-image": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Draw image

Shows one or more images on the display.

---

Draws each given \`tile:tile.parameter->microbit-v2.image\` in order, holding
each for \`tile:tile.parameter->microbit-v2.duration\` seconds (default 1
second); the last image stays on the display. With no image it draws
\`tile:tile.literal->struct:<Image>->happy\`. The rule waits for the hold to
finish, and a draw made while the display is busy is dropped; add
\`tile:tile.modifier->microbit-v2.immediately\` to take over the display at once,
or \`tile:tile.modifier->microbit-v2.in-background\` to let the rule continue
without waiting. A duration of 0 paints the image and continues at once.
`,
  "actuator-play-sound": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Play sound

Plays a built-in sound on the speaker.

---

Plays the given \`tile:tile.parameter->microbit-v2.sound-emoji\`, a built-in
sound such as \`tile:tile.literal->struct:<SoundEmoji>->twinkle\`. With no sound
it plays \`tile:tile.literal->struct:<SoundEmoji>->hello\`. The rule waits until
the sound finishes, and a play made while the speaker is busy is dropped; add
\`tile:tile.modifier->microbit-v2.immediately\` to take over the speaker at
once, or \`tile:tile.modifier->microbit-v2.in-background\` to let the rule
continue without waiting.
`,
  "actuator-radio-send": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Radio send

Broadcasts a value to every micro:bit on the same radio group.

---

Sends a number, text, true/false, or a buffer over radio; with no argument it
sends the value the WHEN side produced. A true/false is sent as the number 1
or 0. The receiving micro:bit reads it with the matching radio receive tile and
must be on the same group (see
\`tile:tile.actuator->microbit-v2.set-radio-group\`).
`,
  "actuator-set-pixel": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Set pixel

Sets one LED of the 5x5 display.

---

Lights a single LED. \`tile:tile.parameter->microbit-v2.x\` picks the column and
\`tile:tile.parameter->microbit-v2.y\` the row, each 0 to 4 counted from the top
left (default 0); \`tile:tile.parameter->microbit-v2.brightness\` is 0 (off) to
255 (full, the default). The write is instant and is not blocked by a running
text scroll or image draw.
`,
  "actuator-set-radio-group": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Set radio group

Chooses which radio group this micro:bit talks on.

---

Sets the radio group to a number from 0 to 255; with no argument it sets the
default group 0. Micro:bits only hear each other when their groups match, so
set the same group on both ends, usually when the page is entered.
`,
  "literal-image-arrow-east": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Arrow east

The built-in right-pointing arrow image.

---

A ready-made 5x5 image for \`tile:tile.actuator->microbit-v2.draw-image\`.
`,
  "literal-image-arrow-north": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Arrow north

The built-in up-pointing arrow image.

---

A ready-made 5x5 image for \`tile:tile.actuator->microbit-v2.draw-image\`.
`,
  "literal-image-arrow-south": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Arrow south

The built-in down-pointing arrow image.

---

A ready-made 5x5 image for \`tile:tile.actuator->microbit-v2.draw-image\`.
`,
  "literal-image-arrow-west": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Arrow west

The built-in left-pointing arrow image.

---

A ready-made 5x5 image for \`tile:tile.actuator->microbit-v2.draw-image\`.
`,
  "literal-image-happy": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Happy

The built-in happy face image.

---

A ready-made 5x5 image for \`tile:tile.actuator->microbit-v2.draw-image\`. This is also the image drawn when the draw image tile is given no image.
`,
  "literal-image-heart": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Heart

The built-in heart image.

---

A ready-made 5x5 image for \`tile:tile.actuator->microbit-v2.draw-image\`.
`,
  "literal-image-sad": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Sad

The built-in sad face image.

---

A ready-made 5x5 image for \`tile:tile.actuator->microbit-v2.draw-image\`.
`,
  "literal-sound-giggle": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Giggle

A giggling sound.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "literal-sound-happy": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Happy

A cheerful, upbeat sound.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "literal-sound-hello": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Hello

A short greeting sound.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "literal-sound-mysterious": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Mysterious

A long, eerie sound.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "literal-sound-sad": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Sad

A drooping, unhappy sound.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "literal-sound-slide": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Slide

A sliding-down sound.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "literal-sound-soaring": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Soaring

A long rising flight of sound.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "literal-sound-spring": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Spring

A boingy, bouncing sound.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "literal-sound-twinkle": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Twinkle

A long sparkling chime.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "literal-sound-yawn": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Yawn

A slow, sleepy sound.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "modifier-click": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Click

Reacts to a short press and release.

---

Attach to a button tile such as \`tile:tile.sensor->microbit-v2.button-a\`: the
rule fires when the button is released after a press shorter than one second.
A longer press is a \`tile:tile.modifier->microbit-v2.long-click\` instead.
`,
  "modifier-double-click": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Double click

Reacts to two quick presses.

---

Attach to a button tile such as \`tile:tile.sensor->microbit-v2.button-a\`: the
rule fires when a second press starts within half a second of a click.
`,
  "modifier-face-down": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Face down

Detects the micro:bit lying flat, display down.

---

Attach to \`tile:tile.sensor->microbit-v2.gesture\`: the rule fires while the
board lies flat with the display facing down.
`,
  "modifier-face-up": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Face up

Detects the micro:bit lying flat, display up.

---

Attach to \`tile:tile.sensor->microbit-v2.gesture\`: the rule fires while the
board lies flat with the display facing up.
`,
  "modifier-freefall": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Freefall

Detects the micro:bit falling.

---

Attach to \`tile:tile.sensor->microbit-v2.gesture\`: the rule fires while the
board is falling freely, such as when it is dropped or tossed.
`,
  "modifier-held": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Held

True the whole time a button is down.

---

Attach to a button tile such as \`tile:tile.sensor->microbit-v2.button-a\`: the
rule keeps firing on every think while the button is held, not just on the
press.
`,
  "modifier-immediately": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Immediately

Takes over the display or speaker at once, cutting off whatever was showing or
playing.

---

Attach to \`tile:tile.actuator->microbit-v2.display-scroll\`,
\`tile:tile.actuator->microbit-v2.draw-image\`, or
\`tile:tile.actuator->microbit-v2.play-sound\`: whatever is showing or playing
is stopped and this one starts now. Without it, a request made while the
display or speaker is busy is dropped.
`,
  "modifier-in-background": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# In background

Runs the show or sound just as usual, but the rule does not wait for it: the
rule carries on at once and can fire again, while the display or speaker stays
busy until this one finishes.

---

Attach to \`tile:tile.actuator->microbit-v2.display-scroll\`,
\`tile:tile.actuator->microbit-v2.draw-image\`, or
\`tile:tile.actuator->microbit-v2.play-sound\`: the animation or sound runs as
usual, but the rule continues at once instead of waiting for it to finish. The
display or speaker stays busy until it completes, so a new request during that
time is still dropped.
`,
  "modifier-long-click": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Long click

Reacts to a long press and release.

---

Attach to a button tile such as \`tile:tile.sensor->microbit-v2.button-a\`: the
rule fires when the button is released after being held for one second or more.
`,
  "modifier-pressed": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Pressed

Reacts the moment a button goes down.

---

Attach to a button tile such as \`tile:tile.sensor->microbit-v2.button-a\`: the
rule fires on the think the button is first pressed. This is also what a bare
button tile detects.
`,
  "modifier-released": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Released

Reacts the moment a button comes back up.

---

Attach to a button tile such as \`tile:tile.sensor->microbit-v2.button-a\`: the
rule fires on the think the button is let go.
`,
  "modifier-shake": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Shake

Detects the micro:bit being shaken.

---

Attach to \`tile:tile.sensor->microbit-v2.gesture\` to detect shaking. This is
also what a bare gesture tile detects.
`,
  "modifier-tilt-down": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Tilt down

Detects the micro:bit tilted down.

---

Attach to \`tile:tile.sensor->microbit-v2.gesture\`: the rule fires while the
board is tilted down. It stays true for as long as the board is held in that
position.
`,
  "modifier-tilt-left": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Tilt left

Detects the micro:bit tilted left.

---

Attach to \`tile:tile.sensor->microbit-v2.gesture\`: the rule fires while the
board is tilted left. It stays true for as long as the board is held in that
position.
`,
  "modifier-tilt-right": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Tilt right

Detects the micro:bit tilted right.

---

Attach to \`tile:tile.sensor->microbit-v2.gesture\`: the rule fires while the
board is tilted right. It stays true for as long as the board is held in that
position.
`,
  "modifier-tilt-up": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Tilt up

Detects the micro:bit tilted up.

---

Attach to \`tile:tile.sensor->microbit-v2.gesture\`: the rule fires while the
board is tilted up. It stays true for as long as the board is held in that
position.
`,
  "output-buffer-value": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# The received bytes

The raw bytes that just arrived over radio, for the rule that received it to use.

---

Place \`tile:tile.out->buffer:<buffer>.value\` in the rule whose WHEN is
\`tile:tile.sensor->microbit-v2.radio-receive-buffer\`, or in any rule below it:
it reads the buffer that packet carried. It only has a value on the thinks a
buffer packet arrived.

## See Also

\`tile:tile.sensor->microbit-v2.radio-receive-buffer\`
\`tile:tile.out->number:<number>.rssi\`
`,
  "output-number-rssi": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# The signal strength

How strong the radio signal was for the message that just arrived, as a number
at or below zero: nearer zero is a stronger signal.

---

Place \`tile:tile.out->number:<number>.rssi\` in a rule whose WHEN is any of the
radio receive tiles, or in any rule below it. On a real micro:bit the number
drops further below zero as the sender gets further away, so comparing it
against a number tells a close sender from a distant one. The simulator has no
real signal and reports the same strength for every message.

## See Also

\`tile:tile.sensor->microbit-v2.radio-receive-number\`
\`tile:tile.out->number:<number>.value\`
`,
  "output-number-value": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# The received number

The number that just arrived over radio, for the rule that received it to use.

---

Place \`tile:tile.out->number:<number>.value\` in the rule whose WHEN is
\`tile:tile.sensor->microbit-v2.radio-receive-number\`, or in any rule below it:
it reads the number that packet carried. It only has a value on the thinks a
number packet arrived.

## Example

\`\`\`brain
{
  "ruleJsons": [
    {
      "version": 1,
      "when": [
        "tile.sensor->microbit-v2.radio-receive-number"
      ],
      "do": [
        "tile.actuator->microbit-v2.display-scroll",
        "\${tileId}"
      ],
      "children": [],
      "comment": "Scroll whatever number the other micro:bit sent."
    }
  ],
  "catalog": []
}
\`\`\`

## See Also

\`tile:tile.sensor->microbit-v2.radio-receive-number\`
\`tile:tile.out->number:<number>.rssi\`
`,
  "output-string-value": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# The received text

The text that just arrived over radio, for the rule that received it to use.

---

Place \`tile:tile.out->string:<string>.value\` in the rule whose WHEN is
\`tile:tile.sensor->microbit-v2.radio-receive-string\`, or in any rule below it:
it reads the text that packet carried. It only has a value on the thinks a text
packet arrived.

## See Also

\`tile:tile.sensor->microbit-v2.radio-receive-string\`
\`tile:tile.out->number:<number>.rssi\`
`,
  "parameter-brightness": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Brightness

How brightly an LED lights.

---

Gives \`tile:tile.actuator->microbit-v2.display-set-pixel\` its brightness, a
number from 0 (off) to 255 (full). When left off, the pixel is set to full
brightness; use 0 to turn a pixel off.
`,
  "parameter-duration": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Duration

How long an image is held, in seconds.

---

Gives \`tile:tile.actuator->microbit-v2.draw-image\` its hold time per image, in
seconds. When left off, each image is held for 1 second; a duration of 0
paints the image and lets the rule continue at once.
`,
  "parameter-image": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Image

An image to show on the display.

---

Gives \`tile:tile.actuator->microbit-v2.draw-image\` an image to draw: a built-in
image such as \`tile:tile.literal->struct:<Image>->heart\` or an image variable.
Add more than one to play them in a sequence, each held for the duration.
`,
  "parameter-sound": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Sound

A sound to play on the speaker.

---

Gives \`tile:tile.actuator->microbit-v2.play-sound\` a sound to play: a built-in
sound such as \`tile:tile.literal->struct:<SoundEmoji>->happy\` or a sound
variable.
`,
  "parameter-text": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Text

The text to show on the display.

---

Gives \`tile:tile.actuator->microbit-v2.display-scroll\` the text to scroll.
When left off, the actuator shows the value the WHEN side produced, or
"hello".
`,
  "parameter-x": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# X

The column of a display pixel.

---

Gives \`tile:tile.actuator->microbit-v2.display-set-pixel\` its column, a number
from 0 (left) to 4 (right). When left off, the column is 0.
`,
  "parameter-y": `\`\`\`brain noframe do
{ "tile": "\${tileId}" }
\`\`\`

# Y

The row of a display pixel.

---

Gives \`tile:tile.actuator->microbit-v2.display-set-pixel\` its row, a number
from 0 (top) to 4 (bottom). When left off, the row is 0.
`,
  "sensor-button-a": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Button A

True when something happens on button A.

---

Place on the **WHEN** side to react to button A. The optional modifier picks the
event: \`tile:tile.modifier->microbit-v2.pressed\` (the default) fires on the think
the button goes down, \`tile:tile.modifier->microbit-v2.released\` when it comes
back up, \`tile:tile.modifier->microbit-v2.click\` after a short press,
\`tile:tile.modifier->microbit-v2.double-click\` on two quick presses,
\`tile:tile.modifier->microbit-v2.long-click\` after a press held for a second or
more, and \`tile:tile.modifier->microbit-v2.held\` is true the whole time the
button is down.
`,
  "sensor-button-ab": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Button A+B

True when buttons A and B are used together.

---

Works like \`tile:tile.sensor->microbit-v2.button-a\`, but the press only counts
while **both** buttons are down at the same time. It takes the same optional
event modifiers: \`tile:tile.modifier->microbit-v2.pressed\` (the default),
\`tile:tile.modifier->microbit-v2.released\`,
\`tile:tile.modifier->microbit-v2.click\`,
\`tile:tile.modifier->microbit-v2.double-click\`,
\`tile:tile.modifier->microbit-v2.long-click\`, and
\`tile:tile.modifier->microbit-v2.held\`.
`,
  "sensor-button-b": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Button B

True when something happens on button B.

---

Place on the **WHEN** side to react to button B. The optional modifier picks the
event: \`tile:tile.modifier->microbit-v2.pressed\` (the default) fires on the think
the button goes down, \`tile:tile.modifier->microbit-v2.released\` when it comes
back up, \`tile:tile.modifier->microbit-v2.click\` after a short press,
\`tile:tile.modifier->microbit-v2.double-click\` on two quick presses,
\`tile:tile.modifier->microbit-v2.long-click\` after a press held for a second or
more, and \`tile:tile.modifier->microbit-v2.held\` is true the whole time the
button is down.
`,
  "sensor-gesture": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Gesture

True while the micro:bit is in the selected motion or orientation.

---

Reads the accelerometer and is true while the current gesture matches the
selected modifier word; with no word it detects
\`tile:tile.modifier->microbit-v2.shake\`. The words are
\`tile:tile.modifier->microbit-v2.shake\`,
\`tile:tile.modifier->microbit-v2.tilt-up\`,
\`tile:tile.modifier->microbit-v2.tilt-down\`,
\`tile:tile.modifier->microbit-v2.tilt-left\`,
\`tile:tile.modifier->microbit-v2.tilt-right\`,
\`tile:tile.modifier->microbit-v2.face-up\`,
\`tile:tile.modifier->microbit-v2.face-down\`, and
\`tile:tile.modifier->microbit-v2.freefall\`.
`,
  "sensor-light-level": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Light level

The ambient light shining on the display, from 0 (dark) to 255 (bright).

---

Reads the light falling on the LED matrix each think and reports it as a number
from 0 to 255. On the **WHEN** side it is true whenever the reading is above 0,
so any light makes it fire. The reading is the tile's result, and also fills the
\`value\` output tile for the DO side, so you can compare the brightness against a
threshold, for example to react only when the room goes dark.
`,
  "sensor-logo": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Logo

True when the touch logo is touched.

---

The gold logo on the front of the micro:bit is touch sensitive and behaves like
a third button. It takes the same optional event modifiers as
\`tile:tile.sensor->microbit-v2.button-a\`:
\`tile:tile.modifier->microbit-v2.pressed\` (the default),
\`tile:tile.modifier->microbit-v2.released\`,
\`tile:tile.modifier->microbit-v2.click\`,
\`tile:tile.modifier->microbit-v2.double-click\`,
\`tile:tile.modifier->microbit-v2.long-click\`, and
\`tile:tile.modifier->microbit-v2.held\`.
`,
  "sensor-radio-receive-buffer": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Radio receive buffer

Fires when a buffer of raw bytes arrives over radio.

---

Delivers the next unread buffer packet, one per think, oldest first; the
received bytes are the tile's result, and the packet also fills the
\`received value\` and \`signal strength\` output tiles for the DO side. Buffers
carry custom packet formats, such as the gamepad state packet a library
decodes. Both micro:bits must be on the same radio group (see
\`tile:tile.actuator->microbit-v2.set-radio-group\`).
`,
  "sensor-radio-receive-number": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Radio receive number

Fires when a number arrives over radio.

---

Delivers the next unread number packet, one per think, oldest first; the
received number is the tile's result, and the packet also fills the
\`received value\` and \`signal strength\` output tiles for the DO side. A received
0 still fires the rule. Both micro:bits must be on the same radio group (see
\`tile:tile.actuator->microbit-v2.set-radio-group\`).
`,
  "sensor-radio-receive-string": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Radio receive string

Fires when text arrives over radio.

---

Delivers the next unread text packet, one per think, oldest first; the received
text is the tile's result, and the packet also fills the \`received value\` and
\`signal strength\` output tiles for the DO side. Empty text still fires the
rule. Both micro:bits must be on the same radio group (see
\`tile:tile.actuator->microbit-v2.set-radio-group\`).
`,
  "sensor-temperature": `\`\`\`brain noframe when
{ "tile": "\${tileId}" }
\`\`\`

# Temperature

The temperature of the micro:bit, in degrees Celsius. It can be negative when
the board is cold.

---

Reads the micro:bit's own temperature each think and reports it as a whole
number of degrees Celsius. On the **WHEN** side it is true whenever the reading
is not 0, so it fires at any normal room temperature. The reading is the tile's
result, and also fills the \`value\` output tile for the DO side, so you can
compare it against a threshold, for example to react only when the board gets
warm.
`,
};
